export { default as CookeryCoursesSectionFour } from './popular-courses/CookeryCourse/CookeryCoursesSectionFour'
export { default as CookeryCoursesSectionOne } from './popular-courses/CookeryCourse/CookeryCoursesSectionOne'
export { default as CookeryCoursesSectionThree } from './popular-courses/CookeryCourse/CookeryCoursesSectionThree'
export { default as CookeryCoursesSectionTwo } from './popular-courses/CookeryCourse/CookeryCoursesSectionTwo'
export { default as CookeryCoursesWhyPursueSection } from './popular-courses/CookeryCourse/CookeryCoursesWhyPursueSection'

export { default as NursingCourseSectionOne } from './popular-courses/NursingCourse/NursingCourseSectionOne'
export { default as NursingCourseSectionTwo } from './popular-courses/NursingCourse/NursingCourseSectionTwo'
export { default as NursingCourseSectionThree } from './popular-courses/NursingCourse/NursingCourseSectionThree'
export { default as NursingCourseAboutSection } from './popular-courses/NursingCourse/NursingCourseAboutSection'

export { default as SectionOneOfTeaching } from './popular-courses/teaching/SectionOneOfTeaching'
export { default as SectionTwoOfTeaching } from './popular-courses/teaching/SectionTwoOfTeaching'
export { default as SectionThreeOfTeaching } from './popular-courses/teaching/SectionThreeOfTeaching'
export { default as SectionFourOfTeaching } from './popular-courses/teaching/SectionFourOfTeaching'
export { default as SectionFiveOfTeaching } from './popular-courses/teaching/SectionFiveOfTeaching'

export { default as InformationTechnologySectionOne } from './popular-courses/information-technology/InformationTechnologySectionOne'
export { default as InformationTechnologySectionTwo } from './popular-courses/information-technology/InformationTechnologySectionTwo'
export { default as InformationTechnologySectionThree } from './popular-courses/information-technology/InformationTechnologySectionThree'

export { default as TradeCourseSectionOne } from './popular-courses/trade-course/TradeCourseSectionOne'
export { default as TradeCourseSectionTwo } from './popular-courses/trade-course/TradeCourseSectionTwo'
export { default as TradeCourseSectionThree } from './popular-courses/trade-course/TradeCourseSectionThree'
export { default as TradeCourseSectionFour } from './popular-courses/trade-course/TradeCourseSectionFour'